import Galery from '@/components/images/galery'
import { Button } from '@/components/ui/button'
import prismadb from '@/lib/prismadb'
import { auth, redirectToSignIn } from '@clerk/nextjs'
import Link from 'next/link'

interface ImagePageProps {
  searchParams: {
    query: string
    filter: string
  }
}

const ImagesPage: React.FC<ImagePageProps> = async ({
  searchParams: { query, filter },
}) => {
  const { userId } = auth()

  if (!userId) return redirectToSignIn()

  const images = await prismadb.image.findMany({
    orderBy: {
      createdAt: 'desc',
    },
    where:
      query || filter
        ? {
            AND: [
              {
                OR: [
                  {
                    prompt: {
                      contains: query,
                      mode: 'insensitive',
                    },
                  },
                  {
                    username: {
                      contains: query,
                      mode: 'insensitive',
                    },
                  },
                ],
              },
              {
                size: filter ? parseInt(filter) : undefined,
              },
            ],
            shared: true,
          }
        : { shared: true },
  })

  return (
    <section className='mt-16 max-w-7xl mx-auto h-full'>
      <div className='w-full flex justify-between'>
        <div>
          <h1 className='text-3xl font-extrabold'>Image Gallery</h1>
          <p className='mt-2'>
            Browse through a collection of imaginative and visually
            stunning images generated by DALL-E AI
          </p>
        </div>
        <div className='flex space-x-3 items-center '>
          <Link href='/app/images/generate'>
            <Button>Generate Image</Button>
          </Link>
          <Link href={`/app/images/${userId}`}>
            <Button variant='outline'>My Galery</Button>
          </Link>
        </div>
      </div>
      <div className='mt-16 h-full'>
        <Galery images={images} />
      </div>
    </section>
  )
}

export default ImagesPage
