import Galery from '@/components/images/galery'
import { Button } from '@/components/ui/button'
import prismadb from '@/lib/prismadb'
import { auth } from '@clerk/nextjs/server'
import { Metadata } from 'next'
import Link from 'next/link'

interface ImagePageProps {
  searchParams: {
    query: string
    sizeFilter: string
    modelFilter: string
  }
}

export const metadata: Metadata = {
  title: 'Image Gallery',

  description:
    'Discover the vibrant AI Image Gallery in the BetterGPT Community. Explore unique and creative images generated by AI. Be inspired by the artistic creations of our community members. Join us and unleash your creativity in the world of AI-generated art.',
}

const ImagesPage: React.FC<ImagePageProps> = async (props) => {
  const searchParams = await props.searchParams

  const { query, sizeFilter, modelFilter } = searchParams

  const { userId, redirectToSignIn } = await auth()

  if (!userId) return redirectToSignIn()

  const images = await prismadb.image.findMany({
    orderBy: {
      createdAt: 'desc',
    },
    where:
      query || sizeFilter || modelFilter
        ? {
            AND: [
              {
                OR: [
                  {
                    prompt: {
                      contains: query,
                      mode: 'insensitive',
                    },
                  },
                  {
                    username: {
                      contains: query,
                      mode: 'insensitive',
                    },
                  },
                ],
              },
              {
                size: sizeFilter ? sizeFilter : undefined,
              },
              {
                model: modelFilter ? modelFilter : undefined,
              },
            ],
            shared: true,
          }
        : { shared: true },
  })

  return (
    <section className='mt-16 max-w-7xl mx-auto h-full px-10'>
      <div className='w-full flex flex-col md:flex-row justify-between'>
        <div>
          <h1 className='text-3xl font-extrabold'>Image Gallery</h1>
          <p className='mt-2'>
            Browse through a collection of imaginative and visually
            stunning images generated by DALL-E AI
          </p>
        </div>
        <div className='flex space-x-3 items-center mt-8 md:mt-0'>
          <Link href='/app/images/generate'>
            <Button>Generate Image</Button>
          </Link>
          <Link href={`/app/images/${userId}`}>
            <Button variant='outline'>My Galery</Button>
          </Link>
        </div>
      </div>
      <div className='mt-6 md:mt-16 h-full'>
        <Galery images={images} />
      </div>
    </section>
  )
}

export default ImagesPage
